### ISSUE TITLE
Make jupytext auto-generate .md, not .Rmd

### ISSUE THREAD

**Issue by tordbb** [acntech/vagrant-ml-developer#13]
![image](https://user-images.githubusercontent.com/11409776/91441983-716ae200-e871-11ea-917e-88b45b071921.png)

.Rmd are best for when programming in R, whereas .md are better for Python. 

In `home/vagrant/.jupyter/jupyter_notebook_config.py` , replace the bottom line 
```
c.ContentsManager.default_jupytext_formats=".ipynb,.Rmd"
```
with 
```
c.ContentsManager.default_jupytext_formats=".ipynb,.md"
```

**Comment by martgra** [comment]
changed
