### ISSUE TITLE
Legge til rammeverk matplotlib og TensorFlow Datasets

### ISSUE THREAD

**Issue by mrminy** [acntech/vagrant-ml-developer#5]
For meg ser det ut som om matplotlib ikke har blitt installert i mitt Vagrant image (har bare testet desktop-versjon).

Har derfor to nye forslag til rammeverk som kan legges til:
* matplotlib
* Tensorflow Datasets (tensorflow-datasets)

**Comment by martgra** [comment]
Hei  @mrminy! Korrekt a matplotlib ikke er med. Spørsmålet er om vi kanskje burde lagt "pip-pakker" i en requirements-fil kun. Når man "pakker" disse bildene til vagrantcloud så er de allerede ganske store. Strippe for særlig tensorflow vil spare  endel plass og tid da vagrantcloud har dårlig "nedlasting".

Når man "bygger" hele boksen selv lokalt er dette selvsagt et mindre problem :-)

Hva tenker du?

**Comment by mrminy** [comment]
Det høres ut som en mulighet, ja. Tenker det uansett kan være fint å ha en requirements-fil med de pakkene vi tenker kan være relevante.

**Comment by martgra** [comment]
Lagt til matplotlib og tensorflow-datasets til requirements fil
